// Generated by CoffeeScript 1.6.3
(function() {
  var define, root, _define,
    __hasProp = {}.hasOwnProperty;

  root = typeof this !== "undefined" && this !== null ? this : exports;

  _define = root.define;

  define = function(name, deps, cb) {
    var callback, newroot;
    if (cb == null) {
      if (deps == null) {
        cb = name;
      } else {
        cb = deps;
        deps = name;
      }
    }
    newroot = Object.create(root);
    callback = function() {
      var arg, args, prop, val, _i, _len;
      args = Array.prototype.slice.call(arguments);
      for (_i = 0, _len = args.length; _i < _len; _i++) {
        arg = args[_i];
        if (arg.global != null) {
          for (prop in arg) {
            if (!__hasProp.call(arg, prop)) continue;
            val = arg[prop];
            Object.defineProperty(newroot, prop, {
              value: val
            });
          }
        }
      }
      return cb.apply(newroot, arguments);
    };
    return _define(name, deps, callback);
  };

  root.define = define;

}).call(this);

/*
//@ sourceMappingURL=requireshim.map
*/
